updated 'deploy_vhost', added 'default.configuration' to README, cleanup in run_multihost

diff --git a/deploy_vhost b/deploy_vhost
--- a/deploy_vhost
+++ b/deploy_vhost
@@ -1,96 +1,57 @@
 #!/usr/bin/env bash
 
-# script to run an Apache instance with external config using Docker image with centos7 / Apache / PHP 
-# m.opitz@qmul.ac.uk | 2017-11-16
+# script to deploy a new VHOST to multihost
+# m.opitz@qmul.ac.uk | 2017-11-17
 
-echo v.2.3
-# v.2.1 - added hostmane to container
-# v.2.2 - now removing all other multihost container and serving php5.6 over 80 / 443
+echo v.1.1
 
-usage() { echo "Usage: $0 [-o<c/u>] [-p<7/5>]" 1>&2; exit 1; }
+usage() { echo "Usage: $0 <servername>" 1>&2; exit 1; }
 
-# setup details - most likely to be edited for a new installation
-sites_enabled_path='/home/opitz/workbench/vhosts/sites-enabled'
-www_path=/home/opitz/workbench
-moodledata_path=/home/opitz/workbench/vhosts/moodledata
-filedir_path=/media/opitz/moodledata/filedir
-xchange_path=/home/opitz/workbench/xchange
-db_host_ip=161.23.44.17
-
-while getopts ":p:o:" x; do
-    case "${x}" in
-        o)
-            o=${OPTARG}
-            ;;
-        p)
-            p=${OPTARG}
-            ;;
-        *)
-            usage
-            ;;
-    esac
-done
-shift $((OPTIND-1))
-
-if [ "${p}" == "5" ]
+if [ ! $1 ]
 	then
-	php_v=56
-	port=80
-	ssl_port=443
-else
-	php_v=7
-	port=80
-	ssl_port=443
+	usage
 fi
 
-# remove any exsiting multihost container, running or not
-docker rm -f multihost_centos7_php7_httpd >/dev/null 2>/dev/null
-docker rm -f multihost_centos7_php56_httpd >/dev/null 2>/dev/null
-docker rm -f multihost_ubuntu_php7_apache2 >/dev/null 2>/dev/null
-docker rm -f multihost_ubuntu_php56_apache2 >/dev/null 2>/dev/null
-
-
-if [ "${o}" == "u" ]
+# check for the config file and get the settings
+if [ ! -f /etc/multihost.conf ]
 	then
-	os=ubuntu_php${php_v}_apache2
-	conf_path=/etc/apache2/sites-enabled
-	servername=multihost_${os}
+	echo No configuration file found at /etc/multihost.conf file found - aborting!
+	exit 1
+fi
+. /etc/multihost.conf
 
-#	docker rm -f ${servername} >/dev/null 2>/dev/null
-	docker run -itd \
-		--name ${servername} \
-		-h ${servername} \
-		-p ${port}:80 \
-		-p ${ssl_port}:443 \
-		-v ${sites_enabled_path}:${conf_path} \
-		-v ${www_path}:/var/www \
-		-v ${moodledata_path}:/var/moodledata \
-		-v ${filedir_path}:/filedir \
-		-v ${xchange_path}:/xchange \
-		--add-host db_host:${db_host_ip} \
-		${os}
-	docker exec ${servername} service apache2 restart
-else
-	os=centos7_php${php_v}_httpd
-	conf_path=/etc/httpd/sites-enabled
-	servername=multihost_${os}
+servername=$1
 
-#	docker rm -f ${servername} >/dev/null 2>/dev/null
-	docker run -itd \
-		--privileged=true \
-		--name ${servername} \
-		-h ${servername} \
-		-p ${port}:80 \
-		-p ${ssl_port}:443 \
-		-v /sys/fs/cgroup:/sys/fs/cgroup:ro \
-		-v ${sites_enabled_path}:${conf_path} \
-		-v ${www_path}:/var/www \
-		-v ${moodledata_path}:/var/moodledata \
-		-v ${filedir_path}:/filedir \
-		-v ${xchange_path}:/xchange \
-		--add-host db_host:${db_host_ip} \
-		${os}
-	docker exec ${servername} systemctl start httpd
+if [ -f ${sites_enabled_path}/${servername}.conf ]
+	then
+	echo A server with the name ${servername} already exists - aborting!
+	exit 1
 fi
 
-echo now running ${servername}
+if [ ! -d ${www_path}/${servername} ]
+	then
+	echo No webroot folder found at ${www_path}/${servername} - aborting!
+	exit 1
+fi
+
+if [ ! -f ${sites_enabled_path}/default.configuration ]
+	then
+	echo "Could not find a ${sites_enabled_path}/default.configuration file - aborting!"
+	exit 1
+fi
+
+cp ${sites_enabled_path}/default.configuration ${sites_enabled_path}/${servername}.conf
+sed -i "s/TheServerName/${servername}/g" ${sites_enabled_path}/${servername}.conf
+chmod 777 ${sites_enabled_path}/${servername}.conf
+if [ -d ${moodledata_path}/${servername} ]
+	then
+	sudo rm -r ${moodledata_path}/${servername}
+fi
+mkdir ${moodledata_path}/${servername}
+chmod -R 777 ${moodledata_path}/${servername}
+ln -s ${filedir_path} ${moodledata_path}/${servername}/filedir
+
+reboot_multihost
+
+echo "VHOST ${servername} configured and activated - please add ${servername} to your local /etc/hosts file"
+
