corrected errors in 'multihost_default' command

diff --git a/multihost_default b/multihost_default
--- a/multihost_default
+++ b/multihost_default
@@ -3,7 +3,7 @@
 # script to make one of the VHOSTs teh default server
 # m.opitz@qmul.ac.uk | 2017-11-22
 echo ' '
-echo "multihost default v.1.0"
+echo "multihost default v.1.1"
 echo "---------------------------------------"
 
 usage() { echo "Usage: $0 <servername>" 1>&2; exit 1; }
@@ -17,13 +17,13 @@ servername=$1
 if [ ${servername} == 'html' ]
 	then
 	echo "Cannot replace 'html' with itself - aborting"
-	quit 1
+	exit 1
 fi
 
 # check for the config file and get the settings
 if [ ! -f /etc/multihost.conf ]
 	then
-	echo No configuration file found at /etc/multihost.conf file found - aborting!
+	echo "No configuration found at /etc/multihost.conf  - aborting!"
 	exit 1
 fi
 . /etc/multihost.conf
@@ -31,7 +31,7 @@ fi
 if [ ! -d ${www_path}/${servername} ]
 	then
 	echo "No server found at ${www_path}/${servername} - aborting!"
-	quit 1
+	exit 1
 fi
 
 rm -rf ${www_path}/html 2>/dev/null
